FROM python:3.11-slim

WORKDIR /app

COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY src/ src/
COPY events/ events/

CMD uvicorn src.api:app --host 0.0.0.0 --port ${PORT:-8000}
