"""
Checkpoint 4 validation -- FastAPI endpoints.

Run from project root: python tools/validate_checkpoint_4.py
Exit 0 = all checks passed.

Uses FastAPI TestClient (httpx-backed) to exercise all 7 endpoints in-process.
No uvicorn server required. Lifespan events (startup/shutdown) fire automatically
inside the TestClient context manager.

Pre-condition: events/pipeline_summary.json must exist (generated by process_videos.py).
"""
import json
import os
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from fastapi.testclient import TestClient
from src.api import app

results = []
_REQUIRED_ANOMALY_KEYS = {"type", "severity", "message", "business_recommendation",
                           "triggered_at", "camera", "zone"}


def check(label, fn):
    try:
        detail = fn()
        results.append(("PASS", label, detail or ""))
        return True
    except AssertionError as exc:
        results.append(("FAIL", label, str(exc)))
        return False
    except Exception as exc:
        results.append(("FAIL", label, f"{type(exc).__name__}: {exc}"))
        return False


# All tests run inside a single TestClient context so lifespan fires once.
with TestClient(app) as client:

    # -----------------------------------------------------------------------
    # 1. Startup: lifespan ran (state populated)
    # -----------------------------------------------------------------------
    def _test_startup():
        from src.api import _state
        assert "summary" in _state, "_state['summary'] not populated at startup"
        assert "events"  in _state, "_state['events'] not populated at startup"
        n_events = len(_state["events"])
        n_zones  = len(_state["zone_totals"])
        return f"summary loaded; events={n_events}; zone_totals keys={n_zones}"

    check("API startup: lifespan populated _state from pipeline_summary.json", _test_startup)

    # -----------------------------------------------------------------------
    # 2. GET /health: 200, status="ok"
    # -----------------------------------------------------------------------
    def _test_health_status():
        r = client.get("/health")
        assert r.status_code == 200, f"Expected 200, got {r.status_code}"
        body = r.json()
        assert body.get("status") == "ok", f"Expected status='ok', got {body.get('status')!r}"
        return "status='ok'"

    check("GET /health: returns 200 with status='ok'", _test_health_status)

    # -----------------------------------------------------------------------
    # 3. GET /health: all required keys present
    # -----------------------------------------------------------------------
    def _test_health_keys():
        r = client.get("/health")
        body = r.json()
        required = {
            "status", "timestamp", "uptime_seconds", "events_loaded",
            "transactions_loaded", "last_run", "video_hashes", "log_buffer",
        }
        missing = required - body.keys()
        assert not missing, f"Missing keys: {missing}"
        assert isinstance(body["log_buffer"], list), "log_buffer must be a list"
        assert body["uptime_seconds"] >= 0, "uptime_seconds must be non-negative"
        return f"all {len(required)} keys present; uptime={body['uptime_seconds']}s"

    check("GET /health: all required keys present with correct types", _test_health_keys)

    # -----------------------------------------------------------------------
    # 4. GET /health: video_hashes has exactly 5 entries
    # -----------------------------------------------------------------------
    def _test_health_hashes():
        r = client.get("/health")
        hashes = r.json().get("video_hashes", {})
        assert len(hashes) == 5, f"Expected 5 video hashes, got {len(hashes)}"
        for cam in ["CAM_1", "CAM_2", "CAM_3", "CAM_4", "CAM_5"]:
            assert cam in hashes, f"Missing hash for {cam}"
        return f"5 hashes present: {sorted(hashes.keys())}"

    check("GET /health: video_hashes has 5 entries (one per camera)", _test_health_hashes)

    # -----------------------------------------------------------------------
    # 5. GET /metrics: 200, three sections present
    # -----------------------------------------------------------------------
    def _test_metrics_sections():
        r = client.get("/metrics")
        assert r.status_code == 200, f"Expected 200, got {r.status_code}"
        body = r.json()
        for section in ("traffic", "sales", "operations"):
            assert section in body, f"Missing section: {section}"
        assert body["traffic"].get("data_date") == "16-04-2026"
        assert body["sales"].get("data_date")   == "10-04-2026"
        return "traffic/sales/operations sections present with correct data_date values"

    check("GET /metrics: 200 with traffic/sales/operations sections", _test_metrics_sections)

    # -----------------------------------------------------------------------
    # 6. GET /metrics: sales.gmv > 0
    # -----------------------------------------------------------------------
    def _test_metrics_gmv():
        r = client.get("/metrics")
        gmv = r.json()["sales"].get("gmv", 0)
        assert gmv > 0, f"GMV should be positive, got {gmv}"
        nmv = r.json()["sales"].get("nmv", 0)
        assert nmv > 0, f"NMV should be positive, got {nmv}"
        return f"gmv={gmv}  nmv={nmv}"

    check("GET /metrics: sales.gmv and nmv are positive", _test_metrics_gmv)

    # -----------------------------------------------------------------------
    # 7. GET /funnel: 200, funnel_validation and disclaimer present
    # -----------------------------------------------------------------------
    def _test_funnel():
        r = client.get("/funnel")
        assert r.status_code == 200, f"Expected 200, got {r.status_code}"
        body = r.json()
        fv = body.get("funnel_validation")
        assert fv in ("pass", "warning"), f"funnel_validation must be pass|warning, got {fv!r}"
        assert body.get("disclaimer"), "disclaimer must be a non-empty string"
        assert "zone_visits" in body, "zone_visits missing from funnel"
        assert "avg_dwell_seconds" in body, "avg_dwell_seconds missing from funnel"
        return f"funnel_validation='{fv}' disclaimer present"

    check("GET /funnel: 200 with funnel_validation and disclaimer", _test_funnel)

    # -----------------------------------------------------------------------
    # 8. GET /anomalies: 200, returns list; each item has required keys
    # -----------------------------------------------------------------------
    def _test_anomalies():
        r = client.get("/anomalies")
        assert r.status_code == 200, f"Expected 200, got {r.status_code}"
        body = r.json()
        assert isinstance(body, list), f"Expected list, got {type(body).__name__}"
        for i, a in enumerate(body):
            missing = _REQUIRED_ANOMALY_KEYS - a.keys()
            assert not missing, f"Anomaly {i} missing keys: {missing}"
        return f"{len(body)} anomaly/anomalies; all have required keys"

    check("GET /anomalies: 200 list; each item has all required keys", _test_anomalies)

    # -----------------------------------------------------------------------
    # 9-11. GET /zone_metrics/{zone} for the three dwell zones
    # -----------------------------------------------------------------------
    for _zone, _cam in [("main_floor", "CAM_2"), ("skincare", "CAM_1"), ("billing", "CAM_5")]:
        def _make_dwell_test(z, c):
            def _test():
                r = client.get(f"/zone_metrics/{z}")
                assert r.status_code == 200, f"Expected 200, got {r.status_code}"
                body = r.json()
                assert body.get("zone")   == z, f"zone mismatch: {body.get('zone')!r}"
                assert body.get("camera") == c, f"camera mismatch: {body.get('camera')!r}"
                assert "visit_count"         in body, "visit_count missing"
                assert "avg_dwell_seconds"   in body, "avg_dwell_seconds missing"
                assert "total_dwell_seconds" in body, "total_dwell_seconds missing"
                assert body["visit_count"] >= 0,         "visit_count must be >= 0"
                assert body["total_dwell_seconds"] >= 0, "total_dwell_seconds must be >= 0"
                return (f"visit_count={body['visit_count']}  "
                        f"avg={body['avg_dwell_seconds']}s  "
                        f"total={body['total_dwell_seconds']}s")
            return _test
        check(f"GET /zone_metrics/{_zone}: 200 with visit/dwell fields (Option b total)",
              _make_dwell_test(_zone, _cam))

    # -----------------------------------------------------------------------
    # 12. GET /zone_metrics/entrance: 200, raw + staff-filtered entry counts
    # -----------------------------------------------------------------------
    def _test_zone_entrance():
        r = client.get("/zone_metrics/entrance")
        assert r.status_code == 200, f"Expected 200, got {r.status_code}"
        body = r.json()
        assert body.get("zone")   == "entrance"
        assert body.get("camera") == "CAM_3"
        assert "entry_count_staff_filtered" in body, "entry_count_staff_filtered missing"
        assert "entry_count_raw"            in body, "entry_count_raw missing"
        assert "exit_count_raw"             in body, "exit_count_raw missing"
        assert "note" in body, "note about Q3 status missing"
        return (f"staff_filtered={body['entry_count_staff_filtered']}  "
                f"raw_entry={body['entry_count_raw']}  "
                f"raw_exit={body['exit_count_raw']}")

    check("GET /zone_metrics/entrance: 200 with raw and staff-filtered entry counts",
          _test_zone_entrance)

    # -----------------------------------------------------------------------
    # 13. GET /zone_metrics/warehouse: 200, motion_event_count present
    # -----------------------------------------------------------------------
    def _test_zone_warehouse():
        r = client.get("/zone_metrics/warehouse")
        assert r.status_code == 200, f"Expected 200, got {r.status_code}"
        body = r.json()
        assert body.get("zone")   == "warehouse"
        assert body.get("camera") == "CAM_4"
        assert "motion_event_count" in body, "motion_event_count missing"
        assert body["motion_event_count"] >= 0, "motion_event_count must be >= 0"
        return f"motion_event_count={body['motion_event_count']}"

    check("GET /zone_metrics/warehouse: 200 with motion_event_count",
          _test_zone_warehouse)

    # -----------------------------------------------------------------------
    # 14. GET /zone_metrics/invalid: 404 with valid_zones list
    # -----------------------------------------------------------------------
    def _test_zone_invalid():
        r = client.get("/zone_metrics/does_not_exist")
        assert r.status_code == 404, f"Expected 404, got {r.status_code}"
        body = r.json()
        detail = body.get("detail", {})
        assert "valid_zones" in detail, f"'valid_zones' missing from 404 detail: {detail}"
        vz = detail["valid_zones"]
        assert isinstance(vz, list) and len(vz) == 5, (
            f"valid_zones should be 5-item list, got: {vz}"
        )
        assert "billing" in vz and "entrance" in vz, "valid_zones missing expected zones"
        return f"404 with valid_zones={sorted(vz)}"

    check("GET /zone_metrics/invalid: 404 with valid_zones list", _test_zone_invalid)

    # -----------------------------------------------------------------------
    # 15. GET /events/sample: 200, list of <= 10 events with required envelope
    # -----------------------------------------------------------------------
    def _test_events_sample():
        r = client.get("/events/sample")
        assert r.status_code == 200, f"Expected 200, got {r.status_code}"
        body = r.json()
        assert isinstance(body, list), f"Expected list, got {type(body).__name__}"
        assert len(body) <= 10, f"Sample should have at most 10 events, got {len(body)}"
        if body:
            required_env = {"event_id", "event_type", "camera", "timestamp_seconds", "processed_at"}
            missing = required_env - body[0].keys()
            assert not missing, f"First event missing envelope keys: {missing}"
        return (f"{len(body)} events; "
                f"first event_type={body[0].get('event_type') if body else 'N/A'}")

    check("GET /events/sample: 200 list <= 10 events with valid envelope schema",
          _test_events_sample)

    # -----------------------------------------------------------------------
    # 16. GET /dashboard: 200, all four top-level keys present
    # -----------------------------------------------------------------------
    def _test_dashboard():
        r = client.get("/dashboard")
        assert r.status_code == 200, f"Expected 200, got {r.status_code}"
        body = r.json()
        for key in ("funnel", "anomalies", "metrics", "health"):
            assert key in body, f"Missing top-level key: {key}"
        assert "traffic" in body["metrics"],  "metrics.traffic missing"
        assert "sales"   in body["metrics"],  "metrics.sales missing"
        assert body["health"].get("status") == "ok", "health.status must be 'ok'"
        assert "last_run" in body["health"], "health.last_run missing"
        return "funnel/anomalies/metrics/health all present with correct sub-structure"

    check("GET /dashboard: 200 with all 4 top-level sections", _test_dashboard)

    # -----------------------------------------------------------------------
    # 17. Response times: all 7 endpoints complete in < 500ms
    # -----------------------------------------------------------------------
    def _test_response_times():
        endpoints = [
            "/health", "/metrics", "/funnel", "/anomalies",
            "/zone_metrics/main_floor", "/events/sample", "/dashboard",
        ]
        timings = {}
        for ep in endpoints:
            t0 = time.time()
            r  = client.get(ep)
            ms = round((time.time() - t0) * 1000, 1)
            timings[ep] = ms
            assert ms < 500, f"{ep} took {ms}ms (threshold: 500ms)"
        slowest = max(timings, key=timings.get)
        return (f"all < 500ms; slowest={slowest} at {timings[slowest]}ms")

    check("Response times: all 7 endpoints complete in < 500ms", _test_response_times)

    # -----------------------------------------------------------------------
    # 18. /dashboard omits log_buffer (compact for Streamlit)
    # -----------------------------------------------------------------------
    def _test_dashboard_no_logbuffer():
        r = client.get("/dashboard")
        body = r.json()
        health = body.get("health", {})
        assert "log_buffer" not in health, (
            "/dashboard health sub-dict should not include log_buffer "
            "(kept in /health only for compactness)"
        )
        return "log_buffer absent from /dashboard response (by design)"

    check("GET /dashboard: health sub-dict omits log_buffer (compact design)",
          _test_dashboard_no_logbuffer)


# ── Summary ───────────────────────────────────────────────────────────────────
print()
print("=" * 70)
print("CHECKPOINT 4 VALIDATION -- FastAPI Endpoints")
print("=" * 70)

passed  = sum(1 for r in results if r[0] == "PASS")
failed  = sum(1 for r in results if r[0] == "FAIL")

for status, label, detail in results:
    icon = "v" if status == "PASS" else "X"
    print(f"  [{status}] {icon} {label}")
    if detail:
        d = detail[:120] + "..." if len(detail) > 120 else detail
        print(f"         -> {d}")

print()
print(f"  Result: {passed}/{len(results)} checks passed", end="")
print("  -- ALL PASS" if not failed else f"  ({failed} FAILED)")
print("=" * 70)

sys.exit(0 if failed == 0 else 1)
